"""Generate ``web/seasonal_defaults.js`` from ``data/seasonal_data.json``.

The PWA bundles the default seasonal data so it works fully offline; user
additions live in localStorage on top of these defaults. Keep the two files
in sync by re-running this tool after editing the JSON.

    python tools/sync_seasonal.py
"""

import json
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO_ROOT, "data", "seasonal_data.json")
DST = os.path.join(REPO_ROOT, "web", "seasonal_defaults.js")


def main():
    with open(SRC, "r", encoding="utf-8") as f:
        data = json.load(f)
    js = (
        "// GENERATED by tools/sync_seasonal.py — do not edit by hand.\n"
        "// Source: data/seasonal_data.json (re-run the tool after editing).\n"
        "window.SEASONAL_DEFAULTS = "
        + json.dumps(data, indent=2, ensure_ascii=False)
        + ";\n"
    )
    with open(DST, "w", encoding="utf-8") as f:
        f.write(js)
    print(f"wrote {DST} "
          f"({len(data.get('produce', {}))} produce, "
          f"{len(data.get('festivals', {}))} festivals)")


if __name__ == "__main__":
    main()
