"""Generate ``web/phytochemical_defaults.js`` from ``data/phytochemical_data.json``.

Like ``tools/sync_seasonal.py`` — the PWA bundles the phytochemical inventory
(compound lists, the data disclaimer, and the source link) so it works fully
offline. Keep the two files in sync by re-running this tool after editing the
JSON.

    python tools/sync_phytochemical.py
"""

import json
import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO_ROOT, "data", "phytochemical_data.json")
DST = os.path.join(REPO_ROOT, "web", "phytochemical_defaults.js")


def main():
    with open(SRC, "r", encoding="utf-8") as f:
        data = json.load(f)
    js = (
        "// GENERATED by tools/sync_phytochemical.py — do not edit by hand.\n"
        "// Source: data/phytochemical_data.json (re-run the tool after editing).\n"
        "window.PHYTOCHEMICAL_DEFAULTS = "
        + json.dumps(data, indent=2, ensure_ascii=False)
        + ";\n"
    )
    with open(DST, "w", encoding="utf-8") as f:
        f.write(js)
    rows = sum(len(item.get("compounds", []))
               for item in data.get("items", {}).values())
    print(f"wrote {DST} ({len(data.get('items', {}))} items, {rows} compound rows)")


if __name__ == "__main__":
    main()
