// GENERATED by tools/sync_phytochemical.py — do not edit by hand.
// Source: data/phytochemical_data.json (re-run the tool after editing).
window.PHYTOCHEMICAL_DEFAULTS = {
  "schema_version": 1,
  "values_are_approximate": true,
  "disclaimer": "Data in this inventory is sourced from the USDA FoodData Central database and other public phytochemical references. It is provided as a reference, not as an absolute truth. All databases contain errors, omissions, and variations due to natural factors (soil, climate, cultivar, harvest time, storage, etc.). The values shown are approximations, not lab-verified measurements for your specific plant. Use this data as a guide, not as a prescription.",
  "source": {
    "label": "USDA FoodData Central (fdc.nal.usda.gov)",
    "url": "https://fdc.nal.usda.gov/"
  },
  "items": {
    "tomato": {
      "name": "Tomato",
      "fdc_id": "11529",
      "note": "Values vary widely with cultivar and ripeness; cooking and sun-drying concentrate the lycopene.",
      "compounds": [
        {
          "name": "Lycopene",
          "value": 2.6,
          "unit": "mg/100 g"
        },
        {
          "name": "Beta-carotene",
          "value": 0.45,
          "unit": "mg/100 g"
        },
        {
          "name": "Vitamin C",
          "value": 13.7,
          "unit": "mg/100 g"
        },
        {
          "name": "Quercetin",
          "value": 0.6,
          "unit": "mg/100 g"
        }
      ]
    },
    "zucchini": {
      "name": "Zucchini",
      "fdc_id": "11641",
      "note": "Skin contains more carotenoids than the flesh; values are for raw summer squash.",
      "compounds": [
        {
          "name": "Vitamin C",
          "value": 17.9,
          "unit": "mg/100 g"
        },
        {
          "name": "Lutein + zeaxanthin",
          "value": 2.1,
          "unit": "mg/100 g"
        },
        {
          "name": "Beta-carotene",
          "value": 0.12,
          "unit": "mg/100 g"
        }
      ]
    },
    "porcini": {
      "name": "Porcini Mushroom",
      "note": "Fresh mushrooms are ~90% water; dried ones are far more concentrated, and published values for wild fungi vary widely.",
      "compounds": [
        {
          "name": "Ergothioneine",
          "value": null,
          "unit": "",
          "note": "antioxidant amino acid, present"
        },
        {
          "name": "Beta-glucan",
          "value": null,
          "unit": "",
          "note": "soluble fibre polysaccharide"
        },
        {
          "name": "Vitamin D2",
          "value": null,
          "unit": "",
          "note": "present only when UV-exposed"
        }
      ]
    },
    "asparagus": {
      "name": "Asparagus",
      "fdc_id": "11011",
      "note": "Spear tips concentrate the antioxidants; values fall after storage and cooking.",
      "compounds": [
        {
          "name": "Quercetin",
          "value": 14.0,
          "unit": "mg/100 g"
        },
        {
          "name": "Vitamin C",
          "value": 5.6,
          "unit": "mg/100 g"
        },
        {
          "name": "Folate",
          "value": 52,
          "unit": "µg/100 g"
        },
        {
          "name": "Lutein + zeaxanthin",
          "value": 0.71,
          "unit": "mg/100 g"
        }
      ]
    },
    "strawberry": {
      "name": "Strawberry",
      "fdc_id": "9314",
      "note": "Values are for fresh, ripe berries; sun-ripened fruit carries more anthocyanins.",
      "compounds": [
        {
          "name": "Vitamin C",
          "value": 58.8,
          "unit": "mg/100 g"
        },
        {
          "name": "Pelargonidin (anthocyanin)",
          "value": 19.0,
          "unit": "mg/100 g"
        },
        {
          "name": "Ellagic acid",
          "value": 0.5,
          "unit": "mg/100 g"
        }
      ]
    },
    "elderflower": {
      "name": "Elderflower",
      "note": "The berries are better documented than the flowers; harvest year and drying method change the profile.",
      "compounds": [
        {
          "name": "Rutin",
          "value": null,
          "unit": "",
          "note": "flavonol glycoside prominent in the fresh flowers"
        },
        {
          "name": "Quercetin",
          "value": null,
          "unit": "",
          "note": "aglycone released from glycosides during processing"
        },
        {
          "name": "Chlorogenic acid",
          "value": null,
          "unit": "",
          "note": "hydroxycinnamic acid"
        }
      ]
    },
    "honey": {
      "name": "Honey",
      "fdc_id": "19296",
      "note": "Composition depends entirely on the floral source; dark honeys (buckwheat, heather) are typically richer in phenolics.",
      "compounds": [
        {
          "name": "Total phenolics",
          "value": 15,
          "unit": "mg GAE/100 g"
        },
        {
          "name": "Quercetin",
          "value": null,
          "unit": "",
          "note": "trace flavonoid, floral-source dependent"
        }
      ]
    },
    "chanterelle": {
      "name": "Chanterelle Mushroom",
      "note": "Wild-harvest values depend on the forest and the season.",
      "compounds": [
        {
          "name": "Carotenoids",
          "value": null,
          "unit": "",
          "note": "the yellow colour; provitamin A activity"
        },
        {
          "name": "Ergothioneine",
          "value": null,
          "unit": "",
          "note": "antioxidant amino acid, present"
        },
        {
          "name": "Vitamin D2",
          "value": null,
          "unit": "",
          "note": "increases sharply if dried in UV light"
        }
      ]
    },
    "pomegranate": {
      "name": "Pomegranate",
      "fdc_id": "9442",
      "note": "Most polyphenols are in the peel and pith — the arils alone carry less.",
      "compounds": [
        {
          "name": "Punicalagin (ellagitannin)",
          "value": 190.0,
          "unit": "mg/100 g"
        },
        {
          "name": "Anthocyanins",
          "value": 20.0,
          "unit": "mg/100 g"
        },
        {
          "name": "Vitamin C",
          "value": 10.2,
          "unit": "mg/100 g"
        }
      ]
    },
    "citrus": {
      "name": "Citrus",
      "fdc_id": "746771",
      "note": "Grapefruit is built around naringin instead of hesperidin; the peel contains far more flavanones than the pulp.",
      "compounds": [
        {
          "name": "Vitamin C",
          "value": 59.1,
          "unit": "mg/100 g"
        },
        {
          "name": "Hesperidin (flavanone)",
          "value": 30.0,
          "unit": "mg/100 g"
        },
        {
          "name": "Beta-carotene",
          "value": 0.07,
          "unit": "mg/100 g"
        }
      ]
    },
    "chicken": {
      "name": "Chicken",
      "note": "Animal product — phytochemicals (plant compounds) are not a meaningful reference for meat.",
      "compounds": []
    },
    "lamb": {
      "name": "Spring Lamb",
      "note": "Animal product — no meaningful phytochemical inventory.",
      "compounds": []
    },
    "venison": {
      "name": "Venison",
      "note": "Animal product — no meaningful phytochemical inventory.",
      "compounds": []
    }
  }
};
